pipeline:
  deploy:
    name: deploy
    image: trion/ng-cli-karma
    commands:
      - cd ../
      - ls -la
      - mkdir ./dafnik
      - mv ./myWeb/* ./dafnik
      - mv ./dafnik ./myWeb
      - cd ./myWeb
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - ssh-keyscan -H '$SSH_HOST' >> ~/.ssh/known_hosts
      - echo -e “Host *\n\tStrictHostKeyChecking no\n\n” > ~/.ssh/config
      - scp -P 3730 -o StrictHostKeyChecking=no -rp ./dafnik/* $SSH_USERNAME@$SSH_HOST:/var/www/dafnik > /dev/null
