kind: pipeline
name: default
steps:
- name: scp files
  image: appleboy/drone-scp
  settings:
    host:
      from_secrect: ssh_host
    username:
      from_secrect: ssh_username
    password:
      from_secrect: ssh_password
    port:
      from_secrect: ssh_port
    target: ./*
    source: /var/www/dafnik