kind: pipeline
name: deploying

steps:
  - name: move
    image: trion/ng-cli-karma
    commands:
      - cd ../
      - ls -la
      - mkdir ./dafnik
      - mv ./myWeb/* ./dafnik
      - mv ./dafnik ./myWeb

  - name: scp
    image: appleboy/drone-scp
    settings:
      username: 
        from_secret: ${ssh_username}
      host: "dafnik.me"
      password:
        from_secret: ${ssh_password}
      port:
        from_secret: ${ssh_port}
      command_timeout: 120
      command_timeout: 2m
      target: /var/www/dafnik
      source:
        - myWeb/*
