pipeline:
  move:
    name: move
    image: trion/ng-cli-karma
    commands:
      - cd ../
      - ls -la
      - mkdir ./dafnik
      - mv ./myWeb/* ./dafnik
      - mv ./dafnik ./myWeb

  deploy:
    name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      username: 
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      command_timeout: 120
      command_timeout: 2m
      target: /var/www/dafnik
      source:
        - myWeb/*
