name: Deploy
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy folder to remote
        uses: garygrossgarten/github-action-scp@release
        with:
            local: ./
            remote: /var/www/dafnik
            host: ${{ secrets.SSH_HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.SSH_USER }}
            privateKey: ${{ secrets.SSH_PRIVATE_KEY }}